services:
  local:
    image: local
    secrets:
      - creds
      - creds-cert.pub
    volumes:
      - ${PWD}/local/srv:/root
  remote:
    image: remote
    secrets:
      - creds.pub
    volumes:
      - ${PWD}/remote/srv:/root
secrets:
  creds:
    file: secrets/creds
  creds.pub:
    file: secrets/creds.pub
  creds-cert.pub:
    file: secrets/creds-cert.pub